---
development:
  cloud_name: dueogexpz
  api_key: '573364378773558'
  api_secret: 6R1voNs9w5YY0TiKKIcC6UnGFsY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dueogexpz
  api_key: '573364378773558'
  api_secret: 6R1voNs9w5YY0TiKKIcC6UnGFsY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dueogexpz
  api_key: '573364378773558'
  api_secret: 6R1voNs9w5YY0TiKKIcC6UnGFsY
  enhance_image_tag: true
  static_file_support: false
